# # This workflow will install Python dependencies, run tests and lint with a single version of Python
# # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# name: Flight Price Monitor

# on:
#   # push:
#   #   branches: [ "master" ]
#   # pull_request:
#   #   branches: [ "master" ]
#   # schedule:
#   #   - cron: '*/10 * * * *' # 每 5 分钟运行一次
# permissions:
#   contents: write

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       WXPUSHER_UID: ${{ secrets.WX_UIDS }}  # 注入 Secrets 到环境变量
#       WXPUSHER_TOKEN: ${{ secrets.APPTOKEN }}
#     steps:
#       # 使用到的actions包(用于克隆当前仓库的所有代码)
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           ref: master
#       - name: Set up Python 3.10
#         uses: actions/setup-python@v3
#         with:
#           python-version: "3.10"
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#       - name: Run flight monitor script
#         run: python flight_alert.py # 替换为你的脚本文件名

#       - name: 列出所有文件
#         run: |
#           ls -l
#       - name: Commit changes
#         run: |
#           git config --local user.email "2995265803@qq.com"
#           git config --local user.name "coyomii"
#           git add .
#           git commit -m "Add changes" || echo "No changes to commit"
#           git push origin master
